# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 04:51
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('p', models.IntegerField(verbose_name='Veículo')),
                ('a', models.NullBooleanField()),
                ('data', models.DateTimeField(verbose_name='Hora do registro')),
                ('hr', models.CharField(max_length=5, verbose_name='Hora da SPTrans')),
                ('codigoLinha', models.IntegerField(verbose_name='Código da Linha')),
            ],
        ),
    ]
