# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-05 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronotacografo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='a',
            new_name='acessivel',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='p',
            new_name='prefixo',
        ),
        migrations.AddField(
            model_name='registro',
            name='linha',
            field=models.CharField(default='', max_length=10, verbose_name='Código público da Linha'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='sentidoLinha',
            field=models.IntegerField(default=-1, verbose_name='Sentido da Linha'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registro',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Hora do registro'),
        ),
    ]
