# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronotacografo', '0002_auto_20170805_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='codigoLinha',
            field=models.IntegerField(db_index=True, verbose_name='Código da Linha'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='data',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Hora do registro'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='linha',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Código público da Linha'),
        ),
    ]
