FROM mdillon/postgis:9.6

# Configure o locale para pt_BR
RUN localedef -i pt_BR -c -f UTF-8 -A /usr/share/locale/locale.alias pt_BR.UTF-8
ENV LANG pt_BR.utf8

COPY config/db_init.sh /docker-entrypoint-initdb.d/db_init.sh
