# Este arquivo é usado apenas para desenvolvimento da plataforma
version: "3"
volumes:
  db_data: {}
services:
  web:
    image: laury/monibus:web-dev
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations && python migrate && python /usr/src/app/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    environment:
      DB_HOST: 'db'
      DB_NAME: 'mapa'
      DB_USER: 'postgres'
      DB_PASSWORD: 'senha'
      DEBUG: 'True'
  db:
    image: laury/monibus:db-dev
    build:
      context: ./
      dockerfile: Dockerfile-db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'senha'
      POSTGRES_DB: 'mapa'
